language: android
sudo: false
jdk: oraclejdk8

android:
  components:
      - platform-tools
      - tools
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-android-support

script:
  - ./gradlew assembleRelease
